server:
  port: 8761
  
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: true
    #serviceUrl:
      #defaultZone: http://10.8.1.98:8761/eureka/
    
endpoints:
  shutdown:
    # Actually we don't need authentication
    sensitive: false
    enabled: true
    
management:
  port: 8762
  address: 127.0.0.1


###### eureka metric config ########
metric:
  eureka:
    enabled: true  ##eureka scrape switch
    cluster: 127.0.0.1:8761  ##eureka cluster config
    clusterName: eureka_test  ##eureka cluster name
##appended public labels
publicLabels:
  clusterId: test
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
- pattern: 'Tomcat<type=GlobalRequestProcessor, name=\"(\w+-\w+)-(\d+)\"><>(\w+):'
  name: tomcat_$3_total
  labels:
    port: "$2"
    protocol: "$1"
  help: Tomcat global $3
  type: COUNTER
- pattern: 'Tomcat<j2eeType=Servlet, WebModule=//([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), name=([-a-zA-Z0-9+/$%~_-|!.]*), J2EEApplication=none, J2EEServer=none><>(requestCount|maxTime|processingTime|errorCount):'
  name: tomcat_servlet_$3_total
  labels:
    module: "$1"
    servlet: "$2"
  help: Tomcat servlet $3 total
  type: COUNTER
- pattern: 'Tomcat<type=ThreadPool, name="(\w+-\w+)-(\d+)"><>(currentThreadCount|currentThreadsBusy|keepAliveCount|pollerThreadCount|connectionCount):'
  name: tomcat_threadpool_$3
  labels:
    port: "$2"
    protocol: "$1"
  help: Tomcat threadpool $3
  type: GAUGE
- pattern: 'Tomcat<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions):'
  name: tomcat_session_$3_total
  labels:
    context: "$2"
    host: "$1"
  help: Tomcat session $3 total
  type: COUNTER
- pattern: 'java.lang<type=(OperatingSystem|Memory|Threading|ClassLoading)><>*'
- pattern: 'java.lang<type=GarbageCollector, name=PS \w+><>(CollectionCount|CollectionTime)'
- pattern: 'java.lang<type=Runtime><>(StartTime|UpTime)'
- pattern: 'java.lang<type=MemoryPool><>*'

